// ============================================================================
// Seed New Products for All Categories
// Populates Home & Garden, Beauty, Toys, Sports, Fashion, Electronics, and Computers
// ============================================================================
import { initializeApp } from 'firebase/app';
import { getDatabase, ref, update, set } from 'firebase/database';

const firebaseConfig = {
  apiKey: 'AIzaSyAoBqHmKPsI0re0PbkFQhdhTXQvhltBAIk',
  authDomain: 'clone-ca65e.firebaseapp.com',
  projectId: 'clone-ca65e',
  databaseURL: 'https://clone-ca65e-default-rtdb.firebaseio.com',
  storageBucket: 'clone-ca65e.firebasestorage.app',
  messagingSenderId: '299446199788',
  appId: '1:299446199788:web:f012876ff1644bdd510cc9',
};

const app = initializeApp(firebaseConfig);
const db = getDatabase(app);

export const EXPANDED_CATEGORIES = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Noise-canceling headphones, tablets, gaming consoles, smart speakers, and personal audio.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    itemCount: 12,
  },
  {
    id: 'cat-computers',
    name: 'Computers & Accessories',
    slug: 'computers',
    description: 'Laptops, desktop PCs, curved gaming monitors, mechanical keyboards, and external hard drives.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    itemCount: 14,
  },
  {
    id: 'cat-fashion',
    name: 'Fashion & Apparel',
    slug: 'fashion',
    description: 'Women dresses, men sport coats, kids outfits, gold jewelry, and vegan leather handbags.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    itemCount: 15,
  },
  {
    id: 'cat-home-garden',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Kitchen appliances, cookware sets, robot vacuums, queen pillows, and home decor.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    itemCount: 14,
  },
  {
    id: 'cat-home-kitchen',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Kitchen coffee makers, nonstick pots and pans, robot vacuums, and living room comfort.',
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80',
    itemCount: 14,
  },
  {
    id: 'cat-beauty',
    name: 'Beauty & Personal Care',
    slug: 'beauty',
    description: 'COSRX snail mucin serums, salon hair dryers, matte velvet lipsticks, and luxury perfumes.',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    itemCount: 8,
  },
  {
    id: 'cat-toys',
    name: 'Toys & Games',
    slug: 'toys',
    description: 'Super Mario figures, wooden building blocks, plush teddy bears, and high-speed RC trucks.',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    itemCount: 8,
  },
  {
    id: 'cat-sports',
    name: 'Sports & Outdoors',
    slug: 'sports',
    description: 'Adjustable dumbbells, fitness trackers, athletic moisture-wicking shirts, and premium yoga mats.',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80',
    itemCount: 8,
  },
  {
    id: 'cat-books',
    name: 'Books',
    slug: 'books',
    description: 'Bestselling paperbacks, hardcovers, self-improvement, and timeless business literature.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    itemCount: 6,
  },
];

export const NEW_PRODUCTS = [
  // ── Home & Kitchen / Home & Garden ──────────────────────────────────────────
  {
    id: 'prod-keurig-coffee-maker',
    sku: 'HOM-KEURIG-ELITE',
    title: 'Keurig K-Elite Single-Serve Iced and Hot Coffee Maker, Brushed Slate',
    slug: 'keurig-k-elite-single-serve-coffee-maker',
    description: 'The Keurig K-Elite single serve coffee maker blends a premium brushed finish with programmable features to deliver ultimate beverage customization. Features iced setting for full-flavored iced coffee and hot water on demand.',
    price: 149.99,
    originalPrice: 189.99,
    compareAtPrice: 189.99,
    discountPercent: 21,
    category: 'home-garden',
    categoryName: 'Home & Garden',
    brand: 'Keurig',
    stock: 42,
    status: 'active',
    rating: 4.7,
    reviewCount: 38290,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['kitchen', 'coffee', 'coffee maker', 'home', 'appliances', 'breakfast'],
    features: [
      'Strong Brew button increases strength and bold taste of your coffee',
      'Iced setting brews hot over ice at the touch of a button',
      'Large 75oz removable water reservoir brews 8 cups before refilling',
      'Multiple brew sizes: 4, 6, 8, 10, and 12 oz',
    ],
    specifications: { Brand: 'Keurig', Color: 'Brushed Slate', Capacity: '75 oz', Material: 'Stainless Steel' },
    images: [{ url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80', alt: 'Keurig Coffee Maker on kitchen counter', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-cuisinart-cookware',
    sku: 'HOM-CUIS-11PC',
    title: 'Cuisinart 11-Piece Stainless Steel Kitchen Cookware Pots and Pans Set',
    slug: 'cuisinart-11-piece-cookware-set',
    description: 'Professional grade stainless steel cookware featuring aluminum encapsulated bases that heat quickly and spread heat evenly. Includes saucepans, sauté pan, stockpot, and non-stick skillet with tempered glass covers.',
    price: 199.99,
    originalPrice: 249.99,
    compareAtPrice: 249.99,
    discountPercent: 20,
    category: 'home-garden',
    categoryName: 'Home & Garden',
    brand: 'Cuisinart',
    stock: 35,
    status: 'active',
    rating: 4.8,
    reviewCount: 19400,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['kitchen', 'cookware', 'pots', 'pans', 'cooking', 'home'],
    features: [
      'Classic stainless steel cooking surface will not discolor or alter flavors',
      'Aluminum encapsulated base heats evenly without hot spots',
      'Cool Grip riveted stick handles stay cool on the stovetop',
      'Dishwasher safe and oven safe up to 500°F',
    ],
    specifications: { Brand: 'Cuisinart', Pieces: '11-Piece', Material: 'Stainless Steel' },
    images: [{ url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80', alt: 'Stainless steel cookware pots and pans', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-shark-robot-vacuum',
    sku: 'HOM-SHARK-MATRIX',
    title: 'Shark Matrix Self-Emptying Robot Vacuum & Mop with Precision Home Mapping',
    slug: 'shark-matrix-robot-vacuum-mop',
    description: 'Incredible suction power with Sonic Mopping that scrubs hard floors 100 times per minute. The bagless self-emptying base holds up to 60 days of dirt and debris.',
    price: 399.99,
    originalPrice: 499.99,
    compareAtPrice: 499.99,
    discountPercent: 20,
    category: 'home-garden',
    categoryName: 'Home & Garden',
    brand: 'Shark',
    stock: 18,
    status: 'active',
    rating: 4.6,
    reviewCount: 8430,
    isPrimeEligible: true,
    tags: ['vacuum', 'home', 'living room', 'cleaning', 'robot', 'smart home'],
    features: [
      'Precision Grid Clean takes 2 passes over dirt and pet hair',
      'Sonic Mopping scrubs hard floors 100x per minute for stubborn stains',
      'Bagless self-emptying base holds up to 60 days of dirt',
    ],
    specifications: { Brand: 'Shark', Type: 'Robot Vacuum & Mop', Battery: '120 min runtime' },
    images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&auto=format&fit=crop&q=80', alt: 'Living room with vacuum cleaner', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-beckham-pillows',
    sku: 'HOM-BECK-PLW-2PK',
    title: 'Beckham Hotel Collection Queen Bed Pillows Set of 2, Luxury Cooling Pillows',
    slug: 'beckham-hotel-bed-pillows-queen',
    description: 'Filled with down-alternative fibers and encased in a 250-thread count breathable cover, these luxury bed pillows provide superior comfort and support for back, side, and stomach sleepers.',
    price: 49.99,
    originalPrice: 69.99,
    compareAtPrice: 69.99,
    discountPercent: 28,
    category: 'home-garden',
    categoryName: 'Home & Garden',
    brand: 'Beckham Hotel Collection',
    stock: 80,
    status: 'active',
    rating: 4.7,
    reviewCount: 165000,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['bedding', 'pillows', 'bedroom', 'home', 'sleep'],
    features: [
      '250-Thread count cooling cotton cover',
      'OEKO-TEX Certified down-alternative plush filling',
      'Machine washable and bounce-back shape retention',
    ],
    specifications: { Brand: 'Beckham Hotel Collection', Size: 'Queen (Set of 2)', Fill: 'Down Alternative' },
    images: [{ url: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800&auto=format&fit=crop&q=80', alt: 'Luxury white bed pillows set', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-ceramic-vase',
    sku: 'HOM-CERAMIC-VASE',
    title: 'Modern Ceramic Ribbed Decorative Vase for Living Room & Table Decor',
    slug: 'modern-ceramic-ribbed-decorative-vase',
    description: 'Minimalist Nordic boho ribbed ceramic vase crafted with premium clay. Perfect for pampas grass, dried bouquets, modern dining tables, and entryway living room decor.',
    price: 24.99,
    originalPrice: 34.99,
    compareAtPrice: 34.99,
    discountPercent: 28,
    category: 'home-garden',
    categoryName: 'Home & Garden',
    brand: 'Nordic Living',
    stock: 45,
    status: 'active',
    rating: 4.8,
    reviewCount: 3200,
    isPrimeEligible: true,
    tags: ['decor', 'home', 'living room', 'vase', 'ceramic', 'boho'],
    features: [
      'Handcrafted premium stoneware ceramic with matte beige finish',
      'Textured ribbed exterior with watertight glazed interior',
      'Ideal centerpiece for coffee tables, bookshelves, and mantels',
    ],
    specifications: { Brand: 'Nordic Living', Color: 'Off-White / Beige', Height: '8.5 inches' },
    images: [{ url: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80', alt: 'Modern minimalist ribbed ceramic vase', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Beauty & Personal Care ──────────────────────────────────────────────────
  {
    id: 'prod-cosrx-snail-mucin',
    sku: 'BTY-COSRX-SNAIL96',
    title: 'COSRX Advanced Snail 96 Mucin Power Essence Hydrating Facial Serum',
    slug: 'cosrx-advanced-snail-96-mucin-power-essence',
    description: 'Formulated with 96.3% Snail Secretion Filtrate, this lightweight serum repairs and rejuvenates skin from dryness and aging. Improves skin elasticity, smooths uneven texture, and delivers long-lasting moisture without heavy residue.',
    price: 16.99,
    originalPrice: 25.0,
    compareAtPrice: 25.0,
    discountPercent: 32,
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    brand: 'COSRX',
    stock: 120,
    status: 'active',
    rating: 4.8,
    reviewCount: 98400,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['beauty', 'skincare', 'serum', 'snail mucin', 'hydration', 'face'],
    features: [
      'Contains 96.3% Snail Secretion Filtrate to repair and hydrate skin',
      'Soothes damaged skin, fades dark spots, and plumps fine lines',
      '100% cruelty-free, hypoallergenic, and dermatologist tested',
    ],
    specifications: { Brand: 'COSRX', Volume: '100ml / 3.38 fl.oz', SkinType: 'All Skin Types' },
    images: [{ url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80', alt: 'COSRX Snail Mucin Serum on vanity', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-dyson-hair-dryer',
    sku: 'BTY-IONIC-DRYER',
    title: 'Professional Negative Ionic Salon Hair Dryer & Fast Drying Blower with Diffuser',
    slug: 'professional-ionic-hair-dryer-diffuser',
    description: 'Engineered with a 110,000 RPM high-speed brushless motor that produces 23m/s airflow for ultra-fast drying. Emits 200 million negative ions to eliminate frizz and leave hair silky smooth and radiant.',
    price: 89.99,
    originalPrice: 129.99,
    compareAtPrice: 129.99,
    discountPercent: 30,
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    brand: 'SilkPro',
    stock: 45,
    status: 'active',
    rating: 4.7,
    reviewCount: 14200,
    isPrimeEligible: true,
    tags: ['beauty', 'haircare', 'hair dryer', 'styling', 'salon'],
    features: [
      '110,000 RPM ultra-fast brushless motor dries hair in minutes',
      'Thermo-Control intelligent heat sensor protects hair from heat damage',
      'Includes magnetic magnetic nozzle and curl-enhancing diffuser',
    ],
    specifications: { Brand: 'SilkPro', Color: 'Rose Gold / Matte Grey', Speeds: '3 Heat, 2 Speed' },
    images: [{ url: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=800&auto=format&fit=crop&q=80', alt: 'Professional salon hair styling and dryer', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-maybelline-lipstick',
    sku: 'BTY-VELVET-LIP-SET',
    title: 'Matte Velvet Long-Lasting Liquid Lipstick & Gloss Set (6 Vibrant Shades)',
    slug: 'matte-velvet-liquid-lipstick-set',
    description: 'High-pigment, transfer-proof matte liquid lipstick formula enriched with Vitamin E. Provides comfortable, non-drying 16-hour wear with an ultra-smooth velvety finish.',
    price: 19.99,
    originalPrice: 29.99,
    compareAtPrice: 29.99,
    discountPercent: 33,
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    brand: 'Glamour Luxe',
    stock: 90,
    status: 'active',
    rating: 4.6,
    reviewCount: 22100,
    isPrimeEligible: true,
    tags: ['beauty', 'makeup', 'lipstick', 'cosmetics', 'lips'],
    features: [
      '6 rich, complementary nude, berry, and classic red shades',
      'Waterproof and smudge-proof formula lasts up to 16 hours',
      'Cruelty-free formula enriched with moisturizing jojoba oil',
    ],
    specifications: { Brand: 'Glamour Luxe', Finish: 'Matte Velvet', Count: '6 Liquid Lipsticks' },
    images: [{ url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80', alt: 'Luxury cosmetic lipsticks and makeup kit', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-chanel-parfum',
    sku: 'BTY-PARFUM-100ML',
    title: 'Luxury Eau De Parfum Spray 100ml / 3.4 fl.oz with Bergamot & Vanilla Notes',
    slug: 'luxury-eau-de-parfum-spray-100ml',
    description: 'An alluring, long-lasting oriental floral scent. Top notes of crisp Italian bergamot harmonize with delicate white jasmine, warm sandalwood, and creamy bourbon vanilla.',
    price: 85.0,
    originalPrice: 110.0,
    compareAtPrice: 110.0,
    discountPercent: 22,
    category: 'beauty',
    categoryName: 'Beauty & Personal Care',
    brand: 'Maison Royale',
    stock: 40,
    status: 'active',
    rating: 4.9,
    reviewCount: 9340,
    isPrimeEligible: true,
    tags: ['beauty', 'fragrances', 'perfume', 'scent', 'luxury'],
    features: [
      'Signature scent profile: Bergamot, Jasmine, Cedarwood & Warm Vanilla',
      'Eau de Parfum concentration providing 12+ hour longevity',
      'Presented in a heavy multifaceted crystal spray bottle',
    ],
    specifications: { Brand: 'Maison Royale', Size: '100ml / 3.4 oz', Type: 'Eau de Parfum' },
    images: [{ url: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80', alt: 'Luxury perfume bottle with golden mist', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Toys & Games ────────────────────────────────────────────────────────────
  {
    id: 'prod-mario-figures',
    sku: 'TOY-MARIO-PACK',
    title: 'Super Mario Deluxe Mushroom Kingdom Collectible Action Figures Pack',
    slug: 'super-mario-deluxe-figures-pack',
    description: 'Bring the Nintendo magic home with this deluxe multi-figure set including Mario, Luigi, Princess Peach, Yoshi, and Toad. Each articulated figure stands 2.5 to 4 inches tall with authentic video game details.',
    price: 29.99,
    originalPrice: 39.99,
    compareAtPrice: 39.99,
    discountPercent: 25,
    category: 'toys',
    categoryName: 'Toys & Games',
    brand: 'Nintendo',
    stock: 60,
    status: 'active',
    rating: 4.9,
    reviewCount: 18900,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['toys', 'mario', 'figures', 'nintendo', 'kids', 'games', 'action figures'],
    features: [
      'Includes 5 iconic Mushroom Kingdom characters: Mario, Luigi, Peach, Yoshi, Toad',
      'Articulated head and arms for dynamic action poses',
      'Official licensed Nintendo collectible merchandise',
    ],
    specifications: { Brand: 'Nintendo', Age: '3+ Years', Characters: 'Mario, Luigi, Peach, Yoshi, Toad' },
    images: [{ url: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&auto=format&fit=crop&q=80', alt: 'Super Mario figures on display', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-wooden-blocks',
    sku: 'TOY-WOOD-BLKS-100',
    title: 'Melissa & Doug 100-Piece Classic Solid Wood Building Blocks Set',
    slug: 'melissa-doug-100-piece-wooden-building-blocks',
    description: '100 solid wood blocks in 4 colors and 9 distinct geometric shapes. An indispensable classic early-learning toy for developing spatial intelligence, fine motor skills, and creative problem solving.',
    price: 22.99,
    originalPrice: 27.99,
    compareAtPrice: 27.99,
    discountPercent: 18,
    category: 'toys',
    categoryName: 'Toys & Games',
    brand: 'Melissa & Doug',
    stock: 75,
    status: 'active',
    rating: 4.8,
    reviewCount: 34100,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['toys', 'blocks', 'wooden', 'kids', 'toddlers', 'learning', 'educational'],
    features: [
      '100 durable wooden blocks in red, blue, green, and yellow',
      'Rounded smooth edges with non-toxic child-safe water-based paint',
      'Helps teach shape recognition, balance, and creative engineering',
    ],
    specifications: { Brand: 'Melissa & Doug', Age: '2 - 8 Years', Count: '100 Pieces' },
    images: [{ url: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=800&auto=format&fit=crop&q=80', alt: 'Wooden colorful toy blocks for toddlers', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-gund-plush-bear',
    sku: 'TOY-GUND-BEAR-12',
    title: 'GUND Philbin Classic Stuffed Animal Plush Teddy Bear, 12 inches Soft Brown',
    slug: 'gund-philbin-classic-stuffed-animal-teddy-bear',
    description: 'Features a classic design with paw pad accents and a lovable, curious expression. Incredibly huggable and soft, meeting the highest GUND quality standards for plush toys.',
    price: 26.0,
    originalPrice: 30.0,
    compareAtPrice: 30.0,
    discountPercent: 13,
    category: 'toys',
    categoryName: 'Toys & Games',
    brand: 'GUND',
    stock: 50,
    status: 'active',
    rating: 4.9,
    reviewCount: 28400,
    isPrimeEligible: true,
    tags: ['toys', 'plush', 'teddy bear', 'stuffed animal', 'baby', 'kids'],
    features: [
      'Ultra-soft premium plush material built to high safety standards',
      'Surface-washable construction for easy, hygienic cleaning',
      'Appropriate for ages 1 and up',
    ],
    specifications: { Brand: 'GUND', Height: '12 inches', Color: 'Chocolate Brown' },
    images: [{ url: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=800&auto=format&fit=crop&q=80', alt: 'Soft fluffy plush teddy bear', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-rc-monster-truck',
    sku: 'TOY-RC-TRUCK-4WD',
    title: '1:18 High Speed Remote Control 4WD All-Terrain Monster Truck 40+ km/h',
    slug: 'high-speed-rc-all-terrain-monster-truck',
    description: 'Equipped with a powerful RC380 motor reaching 40+ km/h speeds. 4-wheel independent suspension and anti-skid heavy-duty rubber tires conquer sand, mud, grass, and rocky terrains with ease.',
    price: 49.99,
    originalPrice: 69.99,
    compareAtPrice: 69.99,
    discountPercent: 28,
    category: 'toys',
    categoryName: 'Toys & Games',
    brand: 'TurboTrail',
    stock: 32,
    status: 'active',
    rating: 4.7,
    reviewCount: 6540,
    isPrimeEligible: true,
    tags: ['toys', 'rc car', 'monster truck', 'remote control', 'boys', 'kids'],
    features: [
      'Speeds up to 40+ km/h with 2.4GHz proportional wireless controller',
      'Includes two 7.4V rechargeable batteries for 40+ minutes of run time',
      'Waterproof electronic speed controller and shockproof metal chassis',
    ],
    specifications: { Brand: 'TurboTrail', Scale: '1:18 4WD', TopSpeed: '40 km/h' },
    images: [{ url: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=800&auto=format&fit=crop&q=80', alt: 'RC high speed monster truck', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Sports & Outdoors / Fitness ─────────────────────────────────────────────
  {
    id: 'prod-bowflex-dumbbells',
    sku: 'SPT-BOWFLEX-552',
    title: 'Bowflex SelectTech 552 Adjustable Dumbbells Pair (5 to 52.5 lbs Each)',
    slug: 'bowflex-selecttech-552-adjustable-dumbbells',
    description: 'Combines 15 sets of weights into one compact system with an intuitive selection dial. Adjusts in 2.5 lb increments up to the first 25 lbs, allowing you to gradually increase your strength.',
    price: 379.0,
    originalPrice: 429.0,
    compareAtPrice: 429.0,
    discountPercent: 12,
    category: 'sports',
    categoryName: 'Sports & Outdoors',
    brand: 'Bowflex',
    stock: 22,
    status: 'active',
    rating: 4.8,
    reviewCount: 31200,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['sports', 'fitness', 'dumbbells', 'equipment', 'weights', 'workout'],
    features: [
      'Replaces 15 pairs of traditional dumbbells using a single rapid selection dial',
      'Weight range from 5 to 52.5 lbs per dumbbell',
      'Durable molding around metal plates creates smooth lift-off and quiet workouts',
    ],
    specifications: { Brand: 'Bowflex', WeightRange: '5 - 52.5 lbs each', Material: 'Steel / Thermoplastic Rubber' },
    images: [{ url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80', alt: 'Adjustable dumbbells on gym floor', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-fitbit-charge-6',
    sku: 'SPT-FITBIT-CHG6',
    title: 'Fitbit Charge 6 Fitness & Health Tracker with Heart Rate, GPS, and 7-Day Battery',
    slug: 'fitbit-charge-6-fitness-tracker',
    description: 'Give your routine a boost with Fitbit Charge 6, featuring Google essentials like Maps and Wallet, 40+ exercise modes, real-time heart rate on compatible gym equipment, and ECG health sensors.',
    price: 139.95,
    originalPrice: 159.95,
    compareAtPrice: 159.95,
    discountPercent: 13,
    category: 'sports',
    categoryName: 'Sports & Outdoors',
    brand: 'Fitbit',
    stock: 55,
    status: 'active',
    rating: 4.6,
    reviewCount: 16400,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['sports', 'fitness', 'trackers', 'smartwatch', 'running', 'health'],
    features: [
      'Heart rate on equipment via Bluetooth connectivity',
      'Built-in GPS for pace and distance tracking during outdoor runs',
      'Up to 7 days of battery life on a single charge',
    ],
    specifications: { Brand: 'Fitbit', Model: 'Charge 6', Battery: '7 Days', WaterResistance: '50 Meters' },
    images: [{ url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80', alt: 'Smart fitness tracker band on wrist', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-under-armour-shirt',
    sku: 'SPT-UA-TECH20-BLK',
    title: "Under Armour Men's Tech 2.0 Short-Sleeve Quick-Dry Athletic T-Shirt",
    slug: 'under-armour-mens-tech-2-athletic-tshirt',
    description: 'UA Tech fabric is quick-drying, ultra-soft, and delivers a natural feel. Material wicks sweat & dries really fast with anti-odor technology that prevents the growth of odor-causing microbes.',
    price: 25.0,
    originalPrice: 30.0,
    compareAtPrice: 30.0,
    discountPercent: 17,
    category: 'sports',
    categoryName: 'Sports & Outdoors',
    brand: 'Under Armour',
    stock: 95,
    status: 'active',
    rating: 4.7,
    reviewCount: 88000,
    isPrimeEligible: true,
    tags: ['sports', 'clothing', 'apparel', 'workout', 't-shirt', 'athletic'],
    features: [
      'Ultra-soft UA Tech fabric dries quickly with natural feel',
      'Moisture transport system wicks sweat away from the body',
      'Streamlined modern fit with shaped hem',
    ],
    specifications: { Brand: 'Under Armour', Material: '100% Polyester', Fit: 'Loose Athletic' },
    images: [{ url: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80', alt: 'Black athletic performance shirt', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-gaiam-yoga-mat',
    sku: 'SPT-GAIAM-YOGA-6MM',
    title: 'Gaiam Premium 6mm Extra Thick Non-Slip Reversible Yoga Mat for Exercise',
    slug: 'gaiam-premium-6mm-extra-thick-yoga-mat',
    description: 'Durable and lightweight 6mm thick exercise yoga mat provides extra joint cushioning for yoga, pilates, stretching, and floor workouts. Textured sticky non-slip surface provides excellent traction and superior grip.',
    price: 29.99,
    originalPrice: 39.99,
    compareAtPrice: 39.99,
    discountPercent: 25,
    category: 'sports',
    categoryName: 'Sports & Outdoors',
    brand: 'Gaiam',
    stock: 65,
    status: 'active',
    rating: 4.7,
    reviewCount: 24500,
    isPrimeEligible: true,
    tags: ['sports', 'equipment', 'yoga', 'pilates', 'fitness', 'exercise'],
    features: [
      '6mm thickness provides superior joint support and spine protection',
      'Textured non-slip reversible design with dual distinct patterns',
      'Free from 6P phthalates, latex, and toxic heavy metals',
    ],
    specifications: { Brand: 'Gaiam', Thickness: '6mm', Dimensions: '68" x 24"' },
    images: [{ url: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80', alt: 'Rolled yoga mat with water bottle', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Fashion & Apparel ───────────────────────────────────────────────────────
  {
    id: 'prod-prettygarden-dress',
    sku: 'FAS-WOM-MAXI-DRS',
    title: "PRETTYGARDEN Women's Floral Print Summer V-Neck Bohemian Maxi Dress",
    slug: 'prettygarden-womens-floral-boho-maxi-dress',
    description: 'Flowy, breathable chiffon maxi dress designed with a flattering wrap V-neckline, tie waist belt, and vibrant floral print. Effortlessly transitions from casual summer daytime to evening dinners.',
    price: 38.99,
    originalPrice: 50.99,
    compareAtPrice: 50.99,
    discountPercent: 24,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'PRETTYGARDEN',
    stock: 50,
    status: 'active',
    rating: 4.5,
    reviewCount: 31200,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['fashion', 'women', 'dress', 'apparel', 'summer', 'floral'],
    features: [
      'Lightweight, soft, and breathable chiffon fabric with smooth lining',
      'Elastic high waist with detachable self-tie belt',
      'Flattering ruffled A-line tiered maxi skirt hem',
    ],
    specifications: { Brand: 'PRETTYGARDEN', Material: '100% Polyester', Pattern: 'Floral' },
    images: [{ url: 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&auto=format&fit=crop&q=80', alt: 'Woman wearing summer floral dress', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-coofandy-blazer',
    sku: 'FAS-MEN-SPORT-BLZ',
    title: "COOFANDY Men's Casual Slim Fit Lightweight Sport Coat One-Button Blazer",
    slug: 'coofandy-mens-casual-slim-fit-blazer',
    description: 'Crafted with premium stretch cotton blend fabric. Features a modern notched lapel, one-button closure, dual flap pockets, and tailored silhouette. Pairs seamlessly with denim or chinos.',
    price: 64.99,
    originalPrice: 85.0,
    compareAtPrice: 85.0,
    discountPercent: 24,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'COOFANDY',
    stock: 40,
    status: 'active',
    rating: 4.6,
    reviewCount: 17800,
    isPrimeEligible: true,
    tags: ['fashion', 'men', 'blazer', 'apparel', 'suit', 'jacket'],
    features: [
      'Breathable lightweight twill fabric with subtle stretch for comfort',
      'Notch lapel and single breasted modern one-button closure',
      'Two patch pockets, one chest pocket, and two interior pockets',
    ],
    specifications: { Brand: 'COOFANDY', Material: 'Cotton / Poly Blend', Fit: 'Slim Fit' },
    images: [{ url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&auto=format&fit=crop&q=80', alt: 'Man wearing tailored blazer and sunglasses', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-carters-girls-outfit',
    sku: 'FAS-GRL-OUTFIT-2PC',
    title: "Simple Joys by Carter's Girls' 2-Piece Ruffle Top and Shorts Summer Outfit",
    slug: 'carters-girls-2-piece-summer-outfit',
    description: 'Adorable 2-piece set featuring a flutter sleeve top with matching elastic-waist bloomers/shorts. Made with 100% soft certified organic cotton that stays soft wash after wash.',
    price: 18.5,
    originalPrice: 24.0,
    compareAtPrice: 24.0,
    discountPercent: 23,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: "Carter's",
    stock: 60,
    status: 'active',
    rating: 4.9,
    reviewCount: 12500,
    isPrimeEligible: true,
    tags: ['fashion', 'girls', 'kids', 'apparel', 'outfit', 'summer'],
    features: [
      '100% breathable gentle combed cotton for sensitive skin',
      'Ruffle flutter sleeve top with covered elastic waistband shorts',
      'Machine washable and fade resistant',
    ],
    specifications: { Brand: "Carter's", Material: '100% Cotton', Pieces: '2-Piece Set' },
    images: [{ url: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80', alt: 'Cute two piece girls outfit flatlay', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-calvin-klein-boys-set',
    sku: 'FAS-BOY-DENIM-SET',
    title: "Calvin Klein Boys' 2-Piece Denim Jacket and Stretch Jeans Casual Set",
    slug: 'calvin-klein-boys-denim-jacket-jeans-set',
    description: 'Timeless Calvin Klein cool. Includes a classic button-front blue denim trucker jacket paired with matching durable stretch denim pants engineered for active kids on the go.',
    price: 39.99,
    originalPrice: 55.0,
    compareAtPrice: 55.0,
    discountPercent: 27,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'Calvin Klein',
    stock: 45,
    status: 'active',
    rating: 4.8,
    reviewCount: 9400,
    isPrimeEligible: true,
    tags: ['fashion', 'boys', 'kids', 'apparel', 'denim', 'jeans', 'jacket'],
    features: [
      'Comfort-stretch denim allows unhindered active playtime',
      'Dual chest flap pockets on classic trucker jacket',
      'Adjustable inner elastic waistband on denim trousers',
    ],
    specifications: { Brand: 'Calvin Klein', Material: '98% Cotton, 2% Spandex', Pieces: '2-Piece Set' },
    images: [{ url: 'https://images.unsplash.com/photo-1503944583220-79d8926ad5e2?w=800&auto=format&fit=crop&q=80', alt: 'Boys jacket and jeans casual wear set', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-pavoi-necklace',
    sku: 'FAS-PAVOI-GOLD-CH',
    title: 'PAVOI 14K Gold Plated Paperclip Chain Choker Necklace 16 inch',
    slug: 'pavoi-14k-gold-paperclip-chain-necklace',
    description: 'Minimalist statement paperclip link necklace plated in 14K yellow gold. Hypoallergenic, nickel-free, and lead-free. Perfect for solo daily wear or layered with dainty pendants.',
    price: 14.95,
    originalPrice: 19.99,
    compareAtPrice: 19.99,
    discountPercent: 25,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'PAVOI',
    stock: 110,
    status: 'active',
    rating: 4.7,
    reviewCount: 41200,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['fashion', 'jewelry', 'necklace', 'gold', 'accessories'],
    features: [
      '14K Yellow Gold plating with protective anti-tarnish e-coating',
      'Secure lobster claw clasp with 2-inch extender chain',
      'Crafted from 100% recycled materials in gift-ready jewelry box',
    ],
    specifications: { Brand: 'PAVOI', Plating: '14K Gold', Length: '16" + 2" Extender' },
    images: [{ url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80', alt: '14k gold chain necklace displayed on stone', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-jwpei-handbag',
    sku: 'FAS-JWPEI-GABBI-BAG',
    title: 'JW PEI Gabbi Ruched Vegan Leather Shoulder Hobo Handbag',
    slug: 'jw-pei-gabbi-ruched-shoulder-handbag',
    description: 'The iconic celebrity-loved croissant silhouette. Crafted from smooth vegan leather made from recycled plastic bottles, with magnetic snap closure and gathered ruched handle.',
    price: 79.99,
    originalPrice: 99.0,
    compareAtPrice: 99.0,
    discountPercent: 19,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'JW PEI',
    stock: 35,
    status: 'active',
    rating: 4.7,
    reviewCount: 8900,
    isPrimeEligible: true,
    isFeatured: true,
    tags: ['fashion', 'handbag', 'bag', 'purse', 'accessories', 'luxury'],
    features: [
      'Sustainable vegan leather made with recycled plastic materials',
      'Chic retro 90s ruched croissant shape with magnetic closure',
      'Spacious interior comfortably holds phone, wallet, keys, and cosmetics',
    ],
    specifications: { Brand: 'JW PEI', Color: 'Ivory Beige', Dimensions: '9.6" W x 4.7" H x 2.4" D' },
    images: [{ url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80', alt: 'Luxury beige shoulder handbag', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Electronics & Audio / Gaming ────────────────────────────────────────────
  {
    id: 'prod-ipad-10th-gen',
    sku: 'ELE-IPAD-10GEN-64',
    title: 'Apple iPad (10th Generation) 10.9-inch Liquid Retina Display, 64GB, Wi-Fi 6',
    slug: 'apple-ipad-10th-generation-64gb',
    description: 'Colorfully reimagined and more versatile than ever. Featuring an all-screen 10.9-inch Liquid Retina display, the powerful A14 Bionic chip, landscape 12MP Ultra Wide front camera, and fast USB-C connectivity.',
    price: 349.0,
    originalPrice: 399.0,
    compareAtPrice: 399.0,
    discountPercent: 13,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Apple',
    stock: 45,
    status: 'active',
    rating: 4.8,
    reviewCount: 54100,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['electronics', 'tablets', 'ipad', 'apple', 'tablet', 'screen'],
    features: [
      'Striking 10.9-inch Liquid Retina display with True Tone',
      'A14 Bionic chip with 6-core CPU and 4-core GPU',
      '12MP Wide back camera and Landscape 12MP Ultra Wide front camera with Center Stage',
      'Touch ID built into top button for secure authentication',
    ],
    specifications: { Brand: 'Apple', Storage: '64GB', Screen: '10.9-inch Liquid Retina', Chip: 'A14 Bionic' },
    images: [{ url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&auto=format&fit=crop&q=80', alt: 'Apple iPad on desk with stylus pen', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-ps5-controller',
    sku: 'ELE-PS5-DUALSENSE',
    title: 'PlayStation DualSense Wireless Controller for PS5, Haptic Feedback & Adaptive Triggers',
    slug: 'playstation-dualsense-wireless-controller',
    description: 'Discover a deeper, highly immersive gaming experience that brings the action to life in the palms of your hands. Features dynamic haptic feedback, adaptive triggers, and a built-in microphone, all integrated into an iconic comfortable design.',
    price: 69.99,
    originalPrice: 74.99,
    compareAtPrice: 74.99,
    discountPercent: 7,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Sony',
    stock: 65,
    status: 'active',
    rating: 4.8,
    reviewCount: 92400,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['electronics', 'gaming', 'ps5', 'controller', 'playstation', 'video games'],
    features: [
      'Haptic feedback replaces traditional rumble motors for realistic in-game touch sensations',
      'Dynamic adaptive triggers simulate varying levels of tension when drawing bows or braking',
      'Built-in microphone and 3.5mm headset jack with dedicated mute button',
    ],
    specifications: { Brand: 'Sony PlayStation', Connectivity: 'Bluetooth / USB-C', Platform: 'PS5, PC, Mobile' },
    images: [{ url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80', alt: 'PS5 DualSense Wireless Controller', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-jbl-flip-6',
    sku: 'ELE-JBL-FLIP6-BLK',
    title: 'JBL Flip 6 Portable Waterproof Bluetooth Speaker with Two-Way Speaker System',
    slug: 'jbl-flip-6-portable-waterproof-speaker',
    description: 'Louder, more powerful audio. The 2-way speaker system delivers bold clarity with deep bass via dual pumping passive radiators. IP67 waterproof and dustproof with up to 12 hours of playtime on a single charge.',
    price: 99.95,
    originalPrice: 129.95,
    compareAtPrice: 129.95,
    discountPercent: 23,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'JBL',
    stock: 50,
    status: 'active',
    rating: 4.7,
    reviewCount: 42100,
    isPrimeEligible: true,
    tags: ['electronics', 'speakers', 'bluetooth', 'audio', 'waterproof', 'portable'],
    features: [
      'Engineered 2-way speaker system with racetrack-shaped woofer and separate tweeter',
      'IP67 waterproof and dustproof design built for beach, pool, and outdoor trails',
      'Up to 12 hours of playtime with USB-C fast charging protection',
    ],
    specifications: { Brand: 'JBL', Battery: '12 Hours', WaterResistance: 'IP67 Waterproof' },
    images: [{ url: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80', alt: 'JBL Flip 6 portable speaker', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ── Computers & Workstation Peripherals ───────────────────────────────────────
  {
    id: 'prod-dell-optiplex-desktop',
    sku: 'CMP-DELL-OPTI-PC',
    title: 'Dell OptiPlex Desktop Tower PC (Intel Core i7, 32GB RAM, 1TB NVMe SSD, Win 11 Pro)',
    slug: 'dell-optiplex-desktop-tower-pc-i7-32gb',
    description: 'Engineered for intensive business multitasking, productivity, and content creation. Equipped with a blazing fast Intel Core i7 processor, 32GB high-speed DDR4 RAM, and 1TB lightning-fast NVMe Solid State Drive.',
    price: 649.0,
    originalPrice: 799.0,
    compareAtPrice: 799.0,
    discountPercent: 19,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Dell',
    stock: 20,
    status: 'active',
    rating: 4.7,
    reviewCount: 7800,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['computers', 'desktops', 'desktop', 'pc', 'tower', 'dell', 'workstation'],
    features: [
      'Intel Core i7 high performance processor up to 4.6 GHz',
      '32GB DDR4 RAM guarantees stutter-free multitasking with dozens of apps',
      '1TB ultra-fast PCIe NVMe SSD boots Windows 11 Pro in seconds',
      'Dual DisplayPort, HDMI, Wi-Fi 6, and Gigabit Ethernet support',
    ],
    specifications: { Brand: 'Dell', Processor: 'Intel Core i7', RAM: '32GB DDR4', Storage: '1TB NVMe SSD' },
    images: [{ url: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=800&auto=format&fit=crop&q=80', alt: 'Dell Desktop PC Tower on desk', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 2, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Friday, Oct 16' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-asus-zenbook-laptop',
    sku: 'CMP-ASUS-ZEN-14',
    title: 'ASUS ZenBook 14 Ultra-Thin OLED Laptop, Intel Core Ultra 7, 16GB RAM, 1TB SSD',
    slug: 'asus-zenbook-14-ultra-thin-oled-laptop',
    description: 'Elevate your mobile productivity with the ultraportable ZenBook 14 OLED. Measuring just 14.9 mm thin and 2.6 lbs, it packs a gorgeous 3K 120Hz ASUS Lumina OLED display with all-day battery life.',
    price: 999.99,
    originalPrice: 1199.99,
    compareAtPrice: 1199.99,
    discountPercent: 17,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'ASUS',
    stock: 15,
    status: 'active',
    rating: 4.8,
    reviewCount: 5200,
    isPrimeEligible: true,
    isFeatured: true,
    tags: ['computers', 'laptops', 'laptop', 'asus', 'oled', 'notebook'],
    features: [
      '14-inch 3K (2880 x 1800) 120Hz 16:10 OLED display with 100% DCI-P3 color gamut',
      'Intel Core Ultra 7 processor with dedicated Intel AI Boost NPU',
      'Up to 15 hours of battery life with fast-charging technology',
    ],
    specifications: { Brand: 'ASUS', Display: '14" 3K OLED 120Hz', CPU: 'Intel Core Ultra 7', Weight: '2.6 lbs' },
    images: [{ url: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80', alt: 'Sleek silver laptop on desk', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-seagate-2tb-hdd',
    sku: 'CMP-SEAGATE-2TB',
    title: 'Seagate Portable 2TB External Hard Drive HDD, USB 3.0 for PC, Mac, PlayStation, Xbox',
    slug: 'seagate-portable-2tb-external-hard-drive',
    description: 'Easily store and access 2TB of photos, movies, music, and document archives on the go. Plug-and-play simplicity with drag-and-drop file saving right out of the box via included 18-inch USB 3.0 cable.',
    price: 64.99,
    originalPrice: 79.99,
    compareAtPrice: 79.99,
    discountPercent: 19,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Seagate',
    stock: 85,
    status: 'active',
    rating: 4.7,
    reviewCount: 215000,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['computers', 'hard drives', 'storage', 'hard drive', 'hdd', 'backup', 'pc accessories'],
    features: [
      'Generous 2TB capacity holds hundreds of thousands of photos and files',
      'USB 3.0 plug-and-play simplicity without requiring external power',
      'Works seamlessly with Windows, Mac, and gaming consoles',
    ],
    specifications: { Brand: 'Seagate', Capacity: '2TB', Interface: 'USB 3.0', FormFactor: '2.5 inch' },
    images: [{ url: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80', alt: 'Seagate external hard drive black', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-nulaxy-laptop-stand',
    sku: 'CMP-NULAXY-STAND',
    title: 'Nulaxy Ergonomic Aluminum Laptop Stand, Foldable Multi-Angle Cooling Riser',
    slug: 'nulaxy-ergonomic-aluminum-laptop-stand',
    description: 'Crafted from premium aluminum alloy that supports laptops up to 17.3 inches. Elevates your laptop screen to eye level to alleviate neck and shoulder tension while open ventilation prevents overheating.',
    price: 26.99,
    originalPrice: 35.99,
    compareAtPrice: 35.99,
    discountPercent: 25,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Nulaxy',
    stock: 70,
    status: 'active',
    rating: 4.8,
    reviewCount: 68000,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['computers', 'pc accessories', 'laptop stand', 'ergonomic', 'accessories', 'desk'],
    features: [
      'Universal compatibility fits all laptops from 10 to 17.3 inches',
      'Solid aluminum construction supports up to 22 lbs (10kg)',
      'Silicone anti-skid pads protect laptop from scratches and slipping',
    ],
    specifications: { Brand: 'Nulaxy', Material: 'Aluminum Alloy', Compatibility: '10 - 17.3" Laptops' },
    images: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80', alt: 'Ergonomic laptop stand on desk', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-samsung-odyssey-g5',
    sku: 'CMP-SMSG-ODY-G5',
    title: 'Samsung Odyssey G5 27" Curved QHD (2560x1440) 165Hz 1ms Gaming Monitor',
    slug: 'samsung-odyssey-g5-27-curved-gaming-monitor',
    description: 'Immerse yourself in hyper-realistic gaming with the 1000R curved display that matches the human field of view. QHD resolution delivers 1.7 times the pixel density of Full HD, alongside a 165Hz refresh rate and AMD FreeSync Premium.',
    price: 249.99,
    originalPrice: 319.99,
    compareAtPrice: 319.99,
    discountPercent: 22,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Samsung',
    stock: 25,
    status: 'active',
    rating: 4.6,
    reviewCount: 14500,
    isPrimeEligible: true,
    isFeatured: true,
    tags: ['computers', 'monitors', 'gaming', 'monitor', 'samsung', 'curved display'],
    features: [
      '27-inch 1000R curvature wraps around your vision for total immersion',
      'QHD resolution with HDR10 for crystal-clear visuals and deep blacks',
      '165Hz refresh rate and 1ms response time eliminate lag and motion blur',
    ],
    specifications: { Brand: 'Samsung', Resolution: '2560 x 1440 QHD', RefreshRate: '165Hz', Curvature: '1000R' },
    images: [{ url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80', alt: 'Curved gaming monitor setup with illumination', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 10:00 AM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-steelseries-keyboard',
    sku: 'CMP-STEEL-APEX-PRO',
    title: 'SteelSeries Apex Pro TKL Mechanical Gaming Keyboard, OmniPoint Adjustable Switches',
    slug: 'steelseries-apex-pro-mechanical-keyboard',
    description: 'The world’s fastest mechanical gaming keyboard. Features OmniPoint 2.0 adjustable hypermagnetic switches with 20x faster actuation and 11x faster response times, with an integrated smart OLED display.',
    price: 189.99,
    originalPrice: 219.99,
    compareAtPrice: 219.99,
    discountPercent: 14,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'SteelSeries',
    stock: 30,
    status: 'active',
    rating: 4.8,
    reviewCount: 9200,
    isPrimeEligible: true,
    tags: ['computers', 'keyboards', 'keyboard', 'mechanical keyboard', 'gaming', 'pc accessories'],
    features: [
      'OmniPoint 2.0 switches allow actuation depth customization from 0.2mm to 3.8mm',
      'OLED Smart Display delivers info straight from games and apps',
      'Aircraft-grade Series 5000 aluminum top plate for lifetime durability',
    ],
    specifications: { Brand: 'SteelSeries', SwitchType: 'OmniPoint 2.0 Magnetic', FormFactor: 'Tenkeyless (TKL)' },
    images: [{ url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80', alt: 'RGB mechanical gaming keyboard', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 8:00 PM', standardDeliveryDate: 'Thursday, Oct 15' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-razer-deathadder-v3',
    sku: 'CMP-RAZER-DA-V3',
    title: 'Razer DeathAdder V3 Ultra-Lightweight Ergonomic Gaming Mouse 30,000 DPI',
    slug: 'razer-deathadder-v3-gaming-mouse',
    description: 'Refined in collaboration with top esports pros, the iconic ergonomic shape is now 25% lighter at just 59g. Powered by the Razer Focus Pro 30K Optical Sensor and Gen-3 Optical Switches with zero double-clicking.',
    price: 69.99,
    originalPrice: 79.99,
    compareAtPrice: 79.99,
    discountPercent: 13,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Razer',
    stock: 55,
    status: 'active',
    rating: 4.7,
    reviewCount: 16800,
    isPrimeEligible: true,
    tags: ['computers', 'gaming mouse', 'mouse', 'pc accessories', 'razer', 'gaming'],
    features: [
      '59g ultra-lightweight ergonomic design optimized for competitive gaming',
      'Focus Pro 30K Optical Sensor delivers flawless tracking on any surface including glass',
      'Optical Mouse Switches Gen-3 rated for 90 million clicks with 0.2ms actuation',
    ],
    specifications: { Brand: 'Razer', DPI: '30,000 DPI', Weight: '59 grams' },
    images: [{ url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80', alt: 'Ultra lightweight gaming mouse', isPrimary: true }],
    deliveryInfo: { isFreeDelivery: true, estimatedDays: 1, fastestDeliveryDate: 'Tomorrow, by 12:00 PM', standardDeliveryDate: 'Wednesday, Oct 14' },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

async function seedDatabase() {
  console.log('Seeding categories and expanded products to Firebase RTDB...');
  
  // 1. Update Categories
  for (const cat of EXPANDED_CATEGORIES) {
    await set(ref(db, `categories/${cat.id}`), cat);
    console.log(`Saved category: ${cat.name} (${cat.slug})`);
  }

  // 2. Update Products
  for (const prod of NEW_PRODUCTS) {
    await set(ref(db, `products/${prod.id}`), prod);
    console.log(`Saved product: ${prod.title.slice(0, 40)}...`);
  }

  console.log(`Successfully seeded ${EXPANDED_CATEGORIES.length} categories and ${NEW_PRODUCTS.length} new products!`);
  process.exit(0);
}

seedDatabase().catch((err) => {
  console.error('Seeding failed:', err);
  process.exit(1);
});
