// ============================================================================
// Catalog Seed Data — Categories & Products
// Cloudinary image URLs + realistic specs, variants, pricing, and stock
// ============================================================================
import type { Category, Product } from '@/types';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat-electronics',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Noise-canceling headphones, 4K displays, smart speakers, and personal audio.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    itemCount: 4,
  },
  {
    id: 'cat-computers',
    name: 'Computers & Accessories',
    slug: 'computers',
    description: 'Laptops, productivity monitors, precision mice, and essential workstation gear.',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    itemCount: 3,
  },
  {
    id: 'cat-fashion',
    name: 'Fashion & Apparel',
    slug: 'fashion',
    description: 'Iconic footwear, timeless denim, classic eyewear, and daily lifestyle essentials.',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    itemCount: 3,
  },
  {
    id: 'cat-home-kitchen',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Smart kitchen appliances, automatic vacuums, and premium coffee makers.',
    image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&auto=format&fit=crop&q=80',
    itemCount: 3,
  },
  {
    id: 'cat-books',
    name: 'Books',
    slug: 'books',
    description: 'Bestselling paperbacks, hardcovers, self-improvement, and timeless business literature.',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    itemCount: 2,
  },
];

export const SEED_PRODUCTS: Product[] = [
  // ── Electronics ─────────────────────────────────────────────────────────────
  {
    id: 'prod-sony-wh1000xm5',
    sku: 'SNY-WH1000XM5-BLK',
    title: 'Sony WH-1000XM5 Wireless Noise-Canceling Over-Ear Headphones',
    slug: 'sony-wh-1000xm5-wireless-headphones',
    description:
      'The Sony WH-1000XM5 headphones rewrite the rules for distraction-free listening. Two processors control 8 microphones for unprecedented noise cancellation and exceptional call quality. With newly developed 30mm drivers and lightweight carbon fiber composite, enjoy high-resolution audio tuned to perfection.',
    price: 348.0,
    originalPrice: 399.99,
    compareAtPrice: 399.99,
    discountPercent: 13,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Sony',
    stock: 28,
    status: 'active',
    rating: 4.7,
    reviewCount: 14820,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['headphones', 'bluetooth', 'noise-canceling', 'wireless', 'sony'],
    features: [
      'Industry Leading Noise Cancellation with two processors and 8 microphones',
      'Ultra-comfortable, lightweight design with soft-fit leather',
      'Up to 30-hour battery life with 3-minute quick charge for 3 hours of playback',
      'Crystal clear hands-free calling with 4 beamforming microphones and AI noise reduction',
      'Multipoint connection allows seamless pairing with two devices at once',
    ],
    specifications: {
      Brand: 'Sony',
      'Model Name': 'WH1000XM5',
      Color: 'Black',
      'Form Factor': 'Over Ear',
      Connectivity: 'Bluetooth 5.2, 3.5mm Aux',
      'Battery Life': '30 Hours',
      'Noise Control': 'Active Noise Cancellation',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        alt: 'Sony WH-1000XM5 Wireless Headphones in Black',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
        alt: 'Sony WH-1000XM5 Side Profile and Earcup',
      },
      {
        url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
        alt: 'Sony WH-1000XM5 Folded in Case',
      },
    ],
    variants: [
      {
        id: 'var-sony-black',
        sku: 'SNY-WH1000XM5-BLK',
        title: 'Black',
        price: 348.0,
        compareAtPrice: 399.99,
        stock: 28,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        attributes: { Color: 'Black' },
      },
      {
        id: 'var-sony-silver',
        sku: 'SNY-WH1000XM5-SLV',
        title: 'Platinum Silver',
        price: 348.0,
        compareAtPrice: 399.99,
        stock: 12,
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
        attributes: { Color: 'Platinum Silver' },
      },
      {
        id: 'var-sony-blue',
        sku: 'SNY-WH1000XM5-BLU',
        title: 'Midnight Blue',
        price: 378.0,
        compareAtPrice: 399.99,
        stock: 6,
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
        attributes: { Color: 'Midnight Blue' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 10:00 PM',
      standardDeliveryDate: 'Thursday, Oct 15',
    },
    seller: { id: 'seller-official-sony', name: 'Sony Direct Store', rating: 4.8 },
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-airpods-pro-2',
    sku: 'APL-APP2-USBC',
    title: 'Apple AirPods Pro (2nd Generation) Wireless Earbuds with USB-C MagSafe Case',
    slug: 'apple-airpods-pro-2nd-gen',
    description:
      'AirPods Pro (2nd generation) with USB-C deliver up to 2x more Active Noise Cancellation than the previous generation, with Transparency mode that lets you hear the world around you and all-new Adaptive Audio that dynamically tailors noise control to your environment.',
    price: 189.99,
    originalPrice: 249.0,
    compareAtPrice: 249.0,
    discountPercent: 24,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Apple',
    stock: 45,
    status: 'active',
    rating: 4.8,
    reviewCount: 31200,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['airpods', 'apple', 'earbuds', 'wireless', 'usb-c'],
    features: [
      'Up to 2x more Active Noise Cancellation with H2 chip',
      'Adaptive Audio dynamically blends Transparency and Noise Cancellation',
      'Personalized Spatial Audio with dynamic head tracking',
      'MagSafe Charging Case (USB-C) with Precision Finding and speaker',
      'Dust, sweat, and water resistant (IP54)',
    ],
    specifications: {
      Brand: 'Apple',
      Model: 'AirPods Pro (2nd Gen)',
      Color: 'White',
      Audio: 'Personalized Spatial Audio',
      Connector: 'USB-C',
      'Battery Life': 'Up to 30 hours with case',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&auto=format&fit=crop&q=80',
        alt: 'Apple AirPods Pro 2 with Charging Case',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&auto=format&fit=crop&q=80',
        alt: 'Apple AirPods Pro In Ear Placement',
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 8:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-apple', name: 'Apple Authorized Reseller', rating: 4.9 },
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-echo-dot-5',
    sku: 'AMZ-ECHODOT-5TH',
    title: 'All-new Echo Dot (5th Gen) | Smart speaker with bigger vibrant sound and Alexa',
    slug: 'all-new-echo-dot-5th-gen',
    description:
      'Our best sounding Echo Dot yet — Enjoy an improved audio experience compared to any previous Echo Dot with Alexa for clearer vocals, deeper bass and vibrant sound in any room. Control smart home devices, play music, set timers and more.',
    price: 49.99,
    originalPrice: 59.99,
    compareAtPrice: 59.99,
    discountPercent: 17,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Amazon',
    stock: 90,
    status: 'active',
    rating: 4.6,
    reviewCount: 42300,
    isPrimeEligible: true,
    isBestSeller: false,
    tags: ['alexa', 'echo', 'smart-home', 'speaker'],
    features: [
      'Our best sounding Echo Dot with deeper bass and clear vocals',
      'Voice control your entertainment across Amazon Music, Spotify, Apple Music',
      'Built-in motion and temperature sensors for automated smart routines',
      'Tap to snooze your alarm clock',
    ],
    specifications: {
      Brand: 'Amazon',
      Model: 'Echo Dot (5th Gen)',
      Connectivity: 'Dual-band Wi-Fi & Bluetooth',
      Dimensions: '3.9" x 3.9" x 3.5"',
      Weight: '10.7 oz (304g)',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1543512214-318c7553f230?w=800&auto=format&fit=crop&q=80',
        alt: 'Echo Dot 5th Gen on nightstand',
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-echo-charcoal',
        sku: 'AMZ-ECHODOT-5TH-CHR',
        title: 'Charcoal',
        price: 49.99,
        stock: 50,
        attributes: { Color: 'Charcoal' },
      },
      {
        id: 'var-echo-white',
        sku: 'AMZ-ECHODOT-5TH-WHT',
        title: 'Glacier White',
        price: 49.99,
        stock: 25,
        attributes: { Color: 'Glacier White' },
      },
      {
        id: 'var-echo-blue',
        sku: 'AMZ-ECHODOT-5TH-BLU',
        title: 'Deep Sea Blue',
        price: 49.99,
        stock: 15,
        attributes: { Color: 'Deep Sea Blue' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 2:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: '2026-09-03T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-samsung-oled-65',
    sku: 'SAM-QN65S90C-4K',
    title: 'SAMSUNG 65-Inch Class OLED 4K S90C Series Smart TV with Dolby Atmos',
    slug: 'samsung-65-inch-oled-4k-s90c',
    description:
      'Step up to OLED technology with bold contrast, dramatic sound, and vibrant colors. See your movies, games, and content burst to life with pure blacks and Pantone-validated color fidelity powered by the Neural Quantum Processor with 4K Upscaling.',
    price: 1597.99,
    originalPrice: 2599.99,
    compareAtPrice: 2599.99,
    discountPercent: 39,
    category: 'electronics',
    categoryName: 'Electronics',
    brand: 'Samsung',
    stock: 4, // Low stock test
    status: 'active',
    rating: 4.6,
    reviewCount: 1850,
    isPrimeEligible: true,
    isBestSeller: false,
    tags: ['tv', 'oled', '4k', 'samsung', 'smart-tv'],
    features: [
      'OLED Technology with Neural Quantum Processor with 4K Upscaling',
      'Quantum HDR OLED reveals fine details in deep blacks and vivid brights',
      'Motion Xcelerator Turbo Pro delivers up to 144Hz refresh rate for gaming',
      'Object Tracking Sound Lite & Dolby Atmos 3D audio experience',
    ],
    specifications: {
      Brand: 'Samsung',
      'Screen Size': '65 Inches',
      'Display Technology': 'OLED',
      Resolution: '4K (3840 x 2160)',
      'Refresh Rate': '144 Hz',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&auto=format&fit=crop&q=80',
        alt: 'Samsung 65-inch OLED TV in living room',
        isPrimary: true,
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 3,
      fastestDeliveryDate: 'Saturday, Oct 17',
      standardDeliveryDate: 'Monday, Oct 19',
    },
    seller: { id: 'seller-samsung', name: 'Samsung Electronics', rating: 4.7 },
    createdAt: '2026-09-04T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },

  // ── Computers & Accessories ────────────────────────────────────────────────
  {
    id: 'prod-macbook-air-m3-15',
    sku: 'APL-MBA15-M3-256',
    title: 'Apple 2024 MacBook Air 15-inch Laptop with M3 chip, 8GB Unified Memory, 256GB SSD',
    slug: 'apple-2024-macbook-air-15-inch-m3',
    description:
      'The 15-inch MacBook Air is impossibly thin with an expansive Liquid Retina display. Powered by the M3 chip, with up to 18 hours of battery life and a portable design, you can take work and play anywhere with blazing fast responsiveness.',
    price: 1099.0,
    originalPrice: 1299.0,
    compareAtPrice: 1299.0,
    discountPercent: 15,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Apple',
    stock: 19,
    status: 'active',
    rating: 4.9,
    reviewCount: 3840,
    isPrimeEligible: true,
    isBestSeller: true,
    isFeatured: true,
    tags: ['laptop', 'macbook', 'apple', 'm3', 'ultrabook'],
    features: [
      'Supercharged by Apple M3 chip with 8-core CPU and 10-core GPU',
      'Up to 18 hours of all-day battery life',
      'Brilliant 15.3-inch Liquid Retina display with 500 nits of brightness',
      'MagSafe 3 charging port, two Thunderbolt ports, headphone jack',
      '1080p FaceTime HD camera, three-mic array, six-speaker sound with Spatial Audio',
    ],
    specifications: {
      Brand: 'Apple',
      'Model Name': 'MacBook Air 15',
      Screen: '15.3-Inch Liquid Retina',
      Processor: 'Apple M3 Chip',
      RAM: '8GB Unified Memory',
      Storage: '256GB SSD',
      Weight: '3.3 lbs (1.51 kg)',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
        alt: 'Apple MacBook Air 15 open on clean desk',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
        alt: 'MacBook Air aluminum chassis profile',
      },
    ],
    variants: [
      {
        id: 'var-mba-midnight-256',
        sku: 'APL-MBA15-M3-256-MID',
        title: 'Midnight - 256GB SSD',
        price: 1099.0,
        compareAtPrice: 1299.0,
        stock: 9,
        attributes: { Color: 'Midnight', Storage: '256GB' },
      },
      {
        id: 'var-mba-spacegray-256',
        sku: 'APL-MBA15-M3-256-GRY',
        title: 'Space Gray - 256GB SSD',
        price: 1099.0,
        compareAtPrice: 1299.0,
        stock: 10,
        attributes: { Color: 'Space Gray', Storage: '256GB' },
      },
      {
        id: 'var-mba-starlight-512',
        sku: 'APL-MBA15-M3-512-STR',
        title: 'Starlight - 512GB SSD',
        price: 1299.0,
        compareAtPrice: 1499.0,
        stock: 6,
        attributes: { Color: 'Starlight', Storage: '512GB' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 1:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-apple', name: 'Apple Authorized Reseller', rating: 4.9 },
    createdAt: '2026-09-05T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-logitech-mx-master-3s',
    sku: 'LOG-MXM3S-GRPH',
    title: 'Logitech MX Master 3S Wireless Performance Mouse with Quiet Clicks and 8K DPI',
    slug: 'logitech-mx-master-3s-wireless-mouse',
    description:
      'An icon remastered. Feel every moment of your workflow with Quiet Clicks and an 8,000 DPI track-on-glass sensor. MagSpeed electromagnetic scrolling delivers remarkable speed and precision, and the ergonomic silhouette supports your palm and fingers all day.',
    price: 99.99,
    originalPrice: 119.99,
    compareAtPrice: 119.99,
    discountPercent: 17,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Logitech',
    stock: 55,
    status: 'active',
    rating: 4.7,
    reviewCount: 16900,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['mouse', 'logitech', 'wireless', 'ergonomic', 'mx-master'],
    features: [
      'Quiet Clicks with 90% less click noise',
      '8K DPI any-surface tracking, including on glass',
      'MagSpeed scroll wheel: 1,000 lines per second with pixel-precise stops',
      'Connect up to 3 devices via Bluetooth or Logi Bolt USB receiver',
      'USB-C rechargeable with up to 70 days battery life',
    ],
    specifications: {
      Brand: 'Logitech',
      'Sensor Technology': 'Darkfield High Precision (8000 DPI)',
      Buttons: '7 Buttons (Left/Right-click, Back/Forward, App-Switch, Wheel mode, Middle)',
      'Battery Type': 'Rechargeable Li-Po (500 mAh)',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80',
        alt: 'Logitech MX Master 3S Mouse on desk',
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-mx-graphite',
        sku: 'LOG-MXM3S-GRPH',
        title: 'Graphite',
        price: 99.99,
        stock: 35,
        attributes: { Color: 'Graphite' },
      },
      {
        id: 'var-mx-palegray',
        sku: 'LOG-MXM3S-PGRY',
        title: 'Pale Gray',
        price: 99.99,
        stock: 20,
        attributes: { Color: 'Pale Gray' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 5:00 PM',
      standardDeliveryDate: 'Thursday, Oct 15',
    },
    seller: { id: 'seller-logitech', name: 'Logitech Store', rating: 4.8 },
    createdAt: '2026-09-06T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-dell-ultrasharp-27',
    sku: 'DEL-U2723QE-4K',
    title: 'Dell UltraSharp 27 4K UHD USB-C Hub Monitor (U2723QE) with IPS Black',
    slug: 'dell-ultrasharp-27-4k-monitor',
    description:
      'Be your most productive on this 27-inch 4K monitor featuring brilliant color and contrast with groundbreaking IPS Black technology and a connectivity hub that delivers 90W power charging over a single USB-C cable.',
    price: 519.99,
    originalPrice: 679.99,
    compareAtPrice: 679.99,
    discountPercent: 24,
    category: 'computers',
    categoryName: 'Computers & Accessories',
    brand: 'Dell',
    stock: 0, // OUT OF STOCK TEST PRODUCT
    status: 'out_of_stock',
    rating: 4.6,
    reviewCount: 3100,
    isPrimeEligible: false,
    isBestSeller: false,
    tags: ['monitor', 'dell', '4k', 'usb-c', 'ips-black'],
    features: [
      '27-inch 4K UHD (3840 x 2160) with IPS Black 2000:1 contrast ratio',
      'Wide color coverage: 98% DCI-P3 and VESA DisplayHDR 400',
      'Extensive connectivity: USB-C (up to 90W power delivery), RJ45 Ethernet, DP 1.4, HDMI',
      'ComfortView Plus reduces low blue light without sacrificing color accuracy',
    ],
    specifications: {
      Brand: 'Dell',
      'Screen Size': '27 Inches',
      Resolution: '4K UHD (3840 x 2160)',
      Panel: 'IPS Black',
      Ports: 'USB-C (90W), HDMI, DisplayPort, RJ45 Ethernet, 5x USB-A',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80',
        alt: 'Dell UltraSharp 27 4K Monitor workspace setup',
        isPrimary: true,
      },
    ],
    deliveryInfo: {
      isFreeDelivery: false,
      estimatedDays: 7,
      fastestDeliveryDate: 'Currently Unavailable',
      standardDeliveryDate: 'Currently Unavailable',
    },
    seller: { id: 'seller-dell', name: 'Dell Technologies', rating: 4.6 },
    createdAt: '2026-09-07T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },

  // ── Fashion & Apparel ──────────────────────────────────────────────────────
  {
    id: 'prod-levis-511-slim',
    sku: 'LEV-511-SLIM-DK',
    title: "Levi's Men's 511 Slim Fit Stretch Denim Jeans",
    slug: 'levis-mens-511-slim-fit-jeans',
    description:
      "A modern slim with room to move. Added stretch for all-day comfort. Levi's 511 Slim Fit Jeans are cut close without being too tight, making them the classic versatile staple for casual everyday wear.",
    price: 49.99,
    originalPrice: 69.5,
    compareAtPrice: 69.5,
    discountPercent: 28,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: "Levi's",
    stock: 40,
    status: 'active',
    rating: 4.5,
    reviewCount: 22400,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['jeans', 'levis', 'mens', 'denim', 'clothing'],
    features: [
      '99% Cotton, 1% Elastane for slight flex stretch comfort',
      'Slim from hip to ankle with a low rise waist',
      'Zip fly with button closure and signature 5-pocket styling',
      'Machine washable',
    ],
    specifications: {
      Brand: "Levi's",
      Material: '99% Cotton, 1% Elastane',
      Fit: 'Slim Fit',
      Closure: 'Zipper fly',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80',
        alt: "Levi's 511 Slim Fit Jeans front",
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-levis-30-32',
        sku: 'LEV-511-30-32',
        title: '30W x 32L / Dark Blue',
        price: 49.99,
        compareAtPrice: 69.5,
        stock: 15,
        attributes: { Size: '30W x 32L', Color: 'Dark Wash' },
      },
      {
        id: 'var-levis-32-32',
        sku: 'LEV-511-32-32',
        title: '32W x 32L / Dark Blue',
        price: 49.99,
        compareAtPrice: 69.5,
        stock: 20,
        attributes: { Size: '32W x 32L', Color: 'Dark Wash' },
      },
      {
        id: 'var-levis-34-32',
        sku: 'LEV-511-34-32',
        title: '34W x 32L / Black Wash',
        price: 54.99,
        compareAtPrice: 69.5,
        stock: 5,
        attributes: { Size: '34W x 32L', Color: 'Black Wash' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 2,
      fastestDeliveryDate: 'Wednesday, Oct 14',
      standardDeliveryDate: 'Friday, Oct 16',
    },
    seller: { id: 'seller-levis', name: "Levi's Official Store", rating: 4.8 },
    createdAt: '2026-09-08T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-nike-air-force-1',
    sku: 'NKE-AF1-07-WHT',
    title: "Nike Men's Air Force 1 '07 Low Basketball Sneakers",
    slug: 'nike-air-force-1-07-sneakers',
    description:
      "The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best: crisp leather, bold colors and the perfect amount of flash to make you shine.",
    price: 115.0,
    originalPrice: 130.0,
    compareAtPrice: 130.0,
    discountPercent: 12,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'Nike',
    stock: 22,
    status: 'active',
    rating: 4.8,
    reviewCount: 36200,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['sneakers', 'shoes', 'nike', 'air-force', 'streetwear'],
    features: [
      'Stitched leather overlays on the upper add heritage style, durability and support',
      'Originally designed for performance hoops, Nike Air cushioning adds lightweight comfort',
      'Low-cut silhouette adds a clean, streamlined look',
      'Padded collar feels soft and comfortable around the ankle',
    ],
    specifications: {
      Brand: 'Nike',
      Silhouette: "Air Force 1 '07",
      Upper: 'Real & Synthetic Leather',
      Sole: 'Rubber Cupsole with Air unit',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
        alt: "Nike Air Force 1 '07 athletic sneaker",
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-af1-sz9',
        sku: 'NKE-AF1-WHT-9',
        title: 'Size 9 / Triple White',
        price: 115.0,
        stock: 8,
        attributes: { Size: '9 US', Color: 'Triple White' },
      },
      {
        id: 'var-af1-sz10',
        sku: 'NKE-AF1-WHT-10',
        title: 'Size 10 / Triple White',
        price: 115.0,
        stock: 10,
        attributes: { Size: '10 US', Color: 'Triple White' },
      },
      {
        id: 'var-af1-sz11',
        sku: 'NKE-AF1-WHT-11',
        title: 'Size 11 / Triple White',
        price: 115.0,
        stock: 4,
        attributes: { Size: '11 US', Color: 'Triple White' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 9:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-nike', name: 'Nike Retail', rating: 4.9 },
    createdAt: '2026-09-09T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-rayban-aviator',
    sku: 'RBN-RB3025-GOLD',
    title: 'Ray-Ban Classic Aviator Sunglasses (RB3025) Polarized Metal Frame',
    slug: 'rayban-classic-aviator-sunglasses',
    description:
      'Currently one of the most iconic sunglass models in the world, Ray-Ban Aviator Classic sunglasses were originally designed for U.S. aviators in 1937. Combine great aviator styling with exceptional quality, performance and comfort.',
    price: 163.0,
    originalPrice: 210.0,
    compareAtPrice: 210.0,
    discountPercent: 22,
    category: 'fashion',
    categoryName: 'Fashion & Apparel',
    brand: 'Ray-Ban',
    stock: 14,
    status: 'active',
    rating: 4.7,
    reviewCount: 8900,
    isPrimeEligible: true,
    isBestSeller: false,
    tags: ['sunglasses', 'ray-ban', 'eyewear', 'polarized', 'accessories'],
    features: [
      'Classic crystal glass lenses provide 100% UV400 protection',
      'Durable polished gold metal frame with comfortable acetate temple tips',
      'Includes Ray-Ban branded protective case and cleaning cloth',
    ],
    specifications: {
      Brand: 'Ray-Ban',
      Frame: 'Polished Gold Metal',
      Lens: 'Green Classic G-15',
      'Lens Width': '58 mm',
      Polarization: 'Non-Polarized / Polarized option',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80',
        alt: 'Ray-Ban Classic Aviator Sunglasses on reflective table',
        isPrimary: true,
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 2,
      fastestDeliveryDate: 'Wednesday, Oct 14',
      standardDeliveryDate: 'Friday, Oct 16',
    },
    seller: { id: 'seller-rayban', name: 'Luxottica Group', rating: 4.7 },
    createdAt: '2026-09-10T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },

  // ── Home & Kitchen ─────────────────────────────────────────────────────────
  {
    id: 'prod-ninja-air-fryer-4qt',
    sku: 'NNJ-AF101-4QT',
    title: 'Ninja AF101 Air Fryer that Crisps, Roasts, Reheats, & Dehydrates, 4-Quart Capacity',
    slug: 'ninja-af101-air-fryer-4-quart',
    description:
      'Now there’s a fast and easy way to cook your favorite meals and snacks. The Ninja Air Fryer circulates super-hot air around your food to remove moisture from its surface to give it that golden-brown, crispy finish without all the fat.',
    price: 89.95,
    originalPrice: 129.99,
    compareAtPrice: 129.99,
    discountPercent: 31,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Ninja',
    stock: 35,
    status: 'active',
    rating: 4.8,
    reviewCount: 48900,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['kitchen', 'air-fryer', 'ninja', 'appliances', 'cooking'],
    features: [
      'Guilt-free fried food: up to 75% less fat than traditional frying methods',
      'Wide temperature range: 105°F to 400°F for gentle dehydrating or quick crisping',
      '4-quart ceramic-coated nonstick basket and crisper plate fits 2 lbs of french fries',
      'Dishwasher-safe parts for effortless clean up',
    ],
    specifications: {
      Brand: 'Ninja',
      Capacity: '4 Quarts',
      Color: 'Black/Grey',
      Wattage: '1500 Watts',
      Dimensions: '13.6"D x 11"W x 13.3"H',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
        alt: 'Modern kitchen counter with air fryer appliance',
        isPrimary: true,
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 4:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-ninja', name: 'SharkNinja Official', rating: 4.8 },
    createdAt: '2026-09-11T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-nespresso-vertuoplus',
    sku: 'NES-VRTPLUS-DEL',
    title: "Nespresso VertuoPlus Coffee and Espresso Machine by De'Longhi",
    slug: 'nespresso-vertuoplus-coffee-espresso-machine',
    description:
      'Nespresso VertuoPlus offers freshly brewed coffee with crema as well as delicious, authentic espresso. It conveniently makes five cup sizes at the touch of a button: Alto Coffee, Mug, Gran Lungo, Double Espresso, and Espresso.',
    price: 149.95,
    originalPrice: 199.0,
    compareAtPrice: 199.0,
    discountPercent: 25,
    category: 'home-kitchen',
    categoryName: 'Home & Kitchen',
    brand: 'Nespresso',
    stock: 16,
    status: 'active',
    rating: 4.6,
    reviewCount: 11200,
    isPrimeEligible: true,
    isBestSeller: false,
    tags: ['coffee', 'espresso', 'nespresso', 'kitchen'],
    features: [
      'Versatile automated coffee maker brews 5 cup sizes with Centrifusion extraction',
      'Precision brewing uses barcode technology on the rim of each capsule',
      'Moveable 60 oz. water tank can rotate to the side or rear to fit kitchen counter space',
      'Automatic opening and closing motorized brew head with fast 20-second heat up',
    ],
    specifications: {
      Brand: 'Nespresso',
      'Special Feature': 'Programmable, Removable Tank, Barcode Centrifusion',
      Capacity: '60 Fluid Ounces',
      Color: 'Matte Black',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
        alt: 'Nespresso espresso extraction with golden crema',
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-nesp-black',
        sku: 'NES-VRTPLUS-BLK',
        title: 'Matte Black',
        price: 149.95,
        stock: 10,
        attributes: { Color: 'Matte Black' },
      },
      {
        id: 'var-nesp-titan',
        sku: 'NES-VRTPLUS-TTN',
        title: 'Titan Grey',
        price: 149.95,
        stock: 6,
        attributes: { Color: 'Titan Grey' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 6:00 PM',
      standardDeliveryDate: 'Thursday, Oct 15',
    },
    seller: { id: 'seller-nespresso', name: "Nestlé Nespresso / De'Longhi", rating: 4.8 },
    createdAt: '2026-09-12T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },

  // ── Books ──────────────────────────────────────────────────────────────────
  {
    id: 'prod-atomic-habits',
    sku: 'BOK-ATMHAB-HC',
    title: 'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    slug: 'atomic-habits-james-clear',
    description:
      'No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear, one of the world’s leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.',
    price: 13.79,
    originalPrice: 27.0,
    compareAtPrice: 27.0,
    discountPercent: 49,
    category: 'books',
    categoryName: 'Books',
    brand: 'James Clear',
    stock: 120,
    status: 'active',
    rating: 4.9,
    reviewCount: 114500,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['books', 'bestseller', 'habits', 'psychology', 'self-help'],
    features: [
      '#1 New York Times Bestseller with over 15 million copies sold',
      'Learn how to make time for new habits, overcome lack of motivation and willpower',
      'Design your environment to make success easier',
      'Get back on track when you fall off course',
    ],
    specifications: {
      Author: 'James Clear',
      Publisher: 'Avery (Penguin Random House)',
      Language: 'English',
      'Print Length': '320 Pages',
      Dimensions: '6.25 x 1.1 x 9.3 inches',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
        alt: 'Atomic Habits hardcover book on study desk',
        isPrimary: true,
      },
    ],
    variants: [
      {
        id: 'var-ah-hardcover',
        sku: 'BOK-ATMHAB-HC',
        title: 'Hardcover',
        price: 13.79,
        compareAtPrice: 27.0,
        stock: 80,
        attributes: { Format: 'Hardcover' },
      },
      {
        id: 'var-ah-paperback',
        sku: 'BOK-ATMHAB-PB',
        title: 'Paperback',
        price: 11.99,
        compareAtPrice: 18.0,
        stock: 40,
        attributes: { Format: 'Paperback' },
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 12:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: '2026-09-13T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
  {
    id: 'prod-psychology-of-money',
    sku: 'BOK-PSYMOM-PB',
    title: 'The Psychology of Money: Timeless lessons on wealth, greed, and happiness',
    slug: 'psychology-of-money-morgan-housel',
    description:
      'Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. Award-winning author Morgan Housel shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important topics.',
    price: 12.99,
    originalPrice: 19.99,
    compareAtPrice: 19.99,
    discountPercent: 35,
    category: 'books',
    categoryName: 'Books',
    brand: 'Morgan Housel',
    stock: 65,
    status: 'active',
    rating: 4.8,
    reviewCount: 52300,
    isPrimeEligible: true,
    isBestSeller: true,
    tags: ['books', 'finance', 'investing', 'psychology', 'bestseller'],
    features: [
      'Over 4 million copies sold globally',
      'Timeless wisdom on financial independence, risk, and long-term compound wealth',
      'Accessible, gripping storytelling divided into 19 digestible chapters',
    ],
    specifications: {
      Author: 'Morgan Housel',
      Publisher: 'Harriman House',
      Language: 'English',
      'Print Length': '256 Pages',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=800&auto=format&fit=crop&q=80',
        alt: 'The Psychology of Money book displayed on wooden shelf',
        isPrimary: true,
      },
    ],
    deliveryInfo: {
      isFreeDelivery: true,
      estimatedDays: 1,
      fastestDeliveryDate: 'Tomorrow, by 8:00 PM',
      standardDeliveryDate: 'Wednesday, Oct 14',
    },
    seller: { id: 'seller-amazon', name: 'Amazon.com', rating: 4.9 },
    createdAt: '2026-09-14T10:00:00.000Z',
    updatedAt: '2026-09-20T10:00:00.000Z',
  },
];
